spring:
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 80
---
spring:
  config:
    activate:
      on-profile: pro
server:
  port: 81
---
spring:
  config:
    activate:
      on-profile: test
server:
  port: 82
---

lesson: SpringBoot

enterprise:
  name: cjy
  age: 23
  tel: 10010
  subject:
    - Java
    - 前端
    - 大数据

